version: 0.2
env:
  secrets-manager:
    # ARN : arn:aws:secretsmanager:ap-southeast-1:250738637992:secret:21227004_secretekey-ExXlYo
    LOGIN: 21227004_secretekey :sonartoken
    HOST: 21227004_secretekey :HOST
    Organization: 21227004_secretekey :Organization
    Project: 21227004_secretekey :Project


phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:  
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
