version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
           
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version

            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/flightproject/*.py
            - pylint --disable=C0415 *.py **/*.py
artifacts:
    files:
        - '**/*'
