# Generated by Django 4.2 on 2023-04-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flightid',
            new_name='flight_id',
        ),
    ]
